// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-devops-go-api/azuredevops/v7/testplan (interfaces: Client)

// Package azdosdkmocks is a generated GoMock package.
package azdosdkmocks

import (
	context "context"
	reflect "reflect"

	testplan "github.com/microsoft/azure-devops-go-api/azuredevops/v7/testplan"
	gomock "go.uber.org/mock/gomock"
)

// MockTestplanClient is a mock of Client interface.
type MockTestplanClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestplanClientMockRecorder
	isgomock struct{}
}

// MockTestplanClientMockRecorder is the mock recorder for MockTestplanClient.
type MockTestplanClientMockRecorder struct {
	mock *MockTestplanClient
}

// NewMockTestplanClient creates a new mock instance.
func NewMockTestplanClient(ctrl *gomock.Controller) *MockTestplanClient {
	mock := &MockTestplanClient{ctrl: ctrl}
	mock.recorder = &MockTestplanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestplanClient) EXPECT() *MockTestplanClientMockRecorder {
	return m.recorder
}

// AddTestCasesToSuite mocks base method.
func (m *MockTestplanClient) AddTestCasesToSuite(ctx context.Context, args testplan.AddTestCasesToSuiteArgs) (*[]testplan.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTestCasesToSuite", ctx, args)
	ret0, _ := ret[0].(*[]testplan.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTestCasesToSuite indicates an expected call of AddTestCasesToSuite.
func (mr *MockTestplanClientMockRecorder) AddTestCasesToSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTestCasesToSuite", reflect.TypeOf((*MockTestplanClient)(nil).AddTestCasesToSuite), ctx, args)
}

// CloneTestCase mocks base method.
func (m *MockTestplanClient) CloneTestCase(ctx context.Context, args testplan.CloneTestCaseArgs) (*testplan.CloneTestCaseOperationInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneTestCase", ctx, args)
	ret0, _ := ret[0].(*testplan.CloneTestCaseOperationInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneTestCase indicates an expected call of CloneTestCase.
func (mr *MockTestplanClientMockRecorder) CloneTestCase(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneTestCase", reflect.TypeOf((*MockTestplanClient)(nil).CloneTestCase), ctx, args)
}

// CloneTestPlan mocks base method.
func (m *MockTestplanClient) CloneTestPlan(ctx context.Context, args testplan.CloneTestPlanArgs) (*testplan.CloneTestPlanOperationInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneTestPlan", ctx, args)
	ret0, _ := ret[0].(*testplan.CloneTestPlanOperationInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneTestPlan indicates an expected call of CloneTestPlan.
func (mr *MockTestplanClientMockRecorder) CloneTestPlan(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneTestPlan", reflect.TypeOf((*MockTestplanClient)(nil).CloneTestPlan), ctx, args)
}

// CloneTestSuite mocks base method.
func (m *MockTestplanClient) CloneTestSuite(ctx context.Context, args testplan.CloneTestSuiteArgs) (*testplan.CloneTestSuiteOperationInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneTestSuite", ctx, args)
	ret0, _ := ret[0].(*testplan.CloneTestSuiteOperationInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneTestSuite indicates an expected call of CloneTestSuite.
func (mr *MockTestplanClientMockRecorder) CloneTestSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneTestSuite", reflect.TypeOf((*MockTestplanClient)(nil).CloneTestSuite), ctx, args)
}

// CreateTestConfiguration mocks base method.
func (m *MockTestplanClient) CreateTestConfiguration(ctx context.Context, args testplan.CreateTestConfigurationArgs) (*testplan.TestConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestConfiguration", ctx, args)
	ret0, _ := ret[0].(*testplan.TestConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTestConfiguration indicates an expected call of CreateTestConfiguration.
func (mr *MockTestplanClientMockRecorder) CreateTestConfiguration(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestConfiguration", reflect.TypeOf((*MockTestplanClient)(nil).CreateTestConfiguration), ctx, args)
}

// CreateTestPlan mocks base method.
func (m *MockTestplanClient) CreateTestPlan(ctx context.Context, args testplan.CreateTestPlanArgs) (*testplan.TestPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestPlan", ctx, args)
	ret0, _ := ret[0].(*testplan.TestPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTestPlan indicates an expected call of CreateTestPlan.
func (mr *MockTestplanClientMockRecorder) CreateTestPlan(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestPlan", reflect.TypeOf((*MockTestplanClient)(nil).CreateTestPlan), ctx, args)
}

// CreateTestSuite mocks base method.
func (m *MockTestplanClient) CreateTestSuite(ctx context.Context, args testplan.CreateTestSuiteArgs) (*testplan.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestSuite", ctx, args)
	ret0, _ := ret[0].(*testplan.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTestSuite indicates an expected call of CreateTestSuite.
func (mr *MockTestplanClientMockRecorder) CreateTestSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestSuite", reflect.TypeOf((*MockTestplanClient)(nil).CreateTestSuite), ctx, args)
}

// CreateTestVariable mocks base method.
func (m *MockTestplanClient) CreateTestVariable(ctx context.Context, args testplan.CreateTestVariableArgs) (*testplan.TestVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestVariable", ctx, args)
	ret0, _ := ret[0].(*testplan.TestVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTestVariable indicates an expected call of CreateTestVariable.
func (mr *MockTestplanClientMockRecorder) CreateTestVariable(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestVariable", reflect.TypeOf((*MockTestplanClient)(nil).CreateTestVariable), ctx, args)
}

// DeleteTestCase mocks base method.
func (m *MockTestplanClient) DeleteTestCase(ctx context.Context, args testplan.DeleteTestCaseArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestCase", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTestCase indicates an expected call of DeleteTestCase.
func (mr *MockTestplanClientMockRecorder) DeleteTestCase(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestCase", reflect.TypeOf((*MockTestplanClient)(nil).DeleteTestCase), ctx, args)
}

// DeleteTestConfguration mocks base method.
func (m *MockTestplanClient) DeleteTestConfguration(ctx context.Context, args testplan.DeleteTestConfgurationArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestConfguration", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTestConfguration indicates an expected call of DeleteTestConfguration.
func (mr *MockTestplanClientMockRecorder) DeleteTestConfguration(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestConfguration", reflect.TypeOf((*MockTestplanClient)(nil).DeleteTestConfguration), ctx, args)
}

// DeleteTestPlan mocks base method.
func (m *MockTestplanClient) DeleteTestPlan(ctx context.Context, args testplan.DeleteTestPlanArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestPlan", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTestPlan indicates an expected call of DeleteTestPlan.
func (mr *MockTestplanClientMockRecorder) DeleteTestPlan(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestPlan", reflect.TypeOf((*MockTestplanClient)(nil).DeleteTestPlan), ctx, args)
}

// DeleteTestSuite mocks base method.
func (m *MockTestplanClient) DeleteTestSuite(ctx context.Context, args testplan.DeleteTestSuiteArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestSuite", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTestSuite indicates an expected call of DeleteTestSuite.
func (mr *MockTestplanClientMockRecorder) DeleteTestSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestSuite", reflect.TypeOf((*MockTestplanClient)(nil).DeleteTestSuite), ctx, args)
}

// DeleteTestVariable mocks base method.
func (m *MockTestplanClient) DeleteTestVariable(ctx context.Context, args testplan.DeleteTestVariableArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestVariable", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTestVariable indicates an expected call of DeleteTestVariable.
func (mr *MockTestplanClientMockRecorder) DeleteTestVariable(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestVariable", reflect.TypeOf((*MockTestplanClient)(nil).DeleteTestVariable), ctx, args)
}

// GetCloneInformation mocks base method.
func (m *MockTestplanClient) GetCloneInformation(ctx context.Context, args testplan.GetCloneInformationArgs) (*testplan.CloneTestPlanOperationInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloneInformation", ctx, args)
	ret0, _ := ret[0].(*testplan.CloneTestPlanOperationInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloneInformation indicates an expected call of GetCloneInformation.
func (mr *MockTestplanClientMockRecorder) GetCloneInformation(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloneInformation", reflect.TypeOf((*MockTestplanClient)(nil).GetCloneInformation), ctx, args)
}

// GetPoints mocks base method.
func (m *MockTestplanClient) GetPoints(ctx context.Context, args testplan.GetPointsArgs) (*[]testplan.TestPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoints", ctx, args)
	ret0, _ := ret[0].(*[]testplan.TestPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoints indicates an expected call of GetPoints.
func (mr *MockTestplanClientMockRecorder) GetPoints(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoints", reflect.TypeOf((*MockTestplanClient)(nil).GetPoints), ctx, args)
}

// GetPointsList mocks base method.
func (m *MockTestplanClient) GetPointsList(ctx context.Context, args testplan.GetPointsListArgs) (*testplan.GetPointsListResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPointsList", ctx, args)
	ret0, _ := ret[0].(*testplan.GetPointsListResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPointsList indicates an expected call of GetPointsList.
func (mr *MockTestplanClientMockRecorder) GetPointsList(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPointsList", reflect.TypeOf((*MockTestplanClient)(nil).GetPointsList), ctx, args)
}

// GetSuiteCloneInformation mocks base method.
func (m *MockTestplanClient) GetSuiteCloneInformation(ctx context.Context, args testplan.GetSuiteCloneInformationArgs) (*testplan.CloneTestSuiteOperationInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuiteCloneInformation", ctx, args)
	ret0, _ := ret[0].(*testplan.CloneTestSuiteOperationInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuiteCloneInformation indicates an expected call of GetSuiteCloneInformation.
func (mr *MockTestplanClientMockRecorder) GetSuiteCloneInformation(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuiteCloneInformation", reflect.TypeOf((*MockTestplanClient)(nil).GetSuiteCloneInformation), ctx, args)
}

// GetSuiteEntries mocks base method.
func (m *MockTestplanClient) GetSuiteEntries(ctx context.Context, args testplan.GetSuiteEntriesArgs) (*[]testplan.SuiteEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuiteEntries", ctx, args)
	ret0, _ := ret[0].(*[]testplan.SuiteEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuiteEntries indicates an expected call of GetSuiteEntries.
func (mr *MockTestplanClientMockRecorder) GetSuiteEntries(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuiteEntries", reflect.TypeOf((*MockTestplanClient)(nil).GetSuiteEntries), ctx, args)
}

// GetSuitesByTestCaseId mocks base method.
func (m *MockTestplanClient) GetSuitesByTestCaseId(ctx context.Context, args testplan.GetSuitesByTestCaseIdArgs) (*[]testplan.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuitesByTestCaseId", ctx, args)
	ret0, _ := ret[0].(*[]testplan.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuitesByTestCaseId indicates an expected call of GetSuitesByTestCaseId.
func (mr *MockTestplanClientMockRecorder) GetSuitesByTestCaseId(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuitesByTestCaseId", reflect.TypeOf((*MockTestplanClient)(nil).GetSuitesByTestCaseId), ctx, args)
}

// GetTestCase mocks base method.
func (m *MockTestplanClient) GetTestCase(ctx context.Context, args testplan.GetTestCaseArgs) (*[]testplan.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestCase", ctx, args)
	ret0, _ := ret[0].(*[]testplan.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestCase indicates an expected call of GetTestCase.
func (mr *MockTestplanClientMockRecorder) GetTestCase(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestCase", reflect.TypeOf((*MockTestplanClient)(nil).GetTestCase), ctx, args)
}

// GetTestCaseCloneInformation mocks base method.
func (m *MockTestplanClient) GetTestCaseCloneInformation(ctx context.Context, args testplan.GetTestCaseCloneInformationArgs) (*testplan.CloneTestCaseOperationInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestCaseCloneInformation", ctx, args)
	ret0, _ := ret[0].(*testplan.CloneTestCaseOperationInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestCaseCloneInformation indicates an expected call of GetTestCaseCloneInformation.
func (mr *MockTestplanClientMockRecorder) GetTestCaseCloneInformation(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestCaseCloneInformation", reflect.TypeOf((*MockTestplanClient)(nil).GetTestCaseCloneInformation), ctx, args)
}

// GetTestCaseList mocks base method.
func (m *MockTestplanClient) GetTestCaseList(ctx context.Context, args testplan.GetTestCaseListArgs) (*testplan.GetTestCaseListResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestCaseList", ctx, args)
	ret0, _ := ret[0].(*testplan.GetTestCaseListResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestCaseList indicates an expected call of GetTestCaseList.
func (mr *MockTestplanClientMockRecorder) GetTestCaseList(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestCaseList", reflect.TypeOf((*MockTestplanClient)(nil).GetTestCaseList), ctx, args)
}

// GetTestConfigurationById mocks base method.
func (m *MockTestplanClient) GetTestConfigurationById(ctx context.Context, args testplan.GetTestConfigurationByIdArgs) (*testplan.TestConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestConfigurationById", ctx, args)
	ret0, _ := ret[0].(*testplan.TestConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestConfigurationById indicates an expected call of GetTestConfigurationById.
func (mr *MockTestplanClientMockRecorder) GetTestConfigurationById(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestConfigurationById", reflect.TypeOf((*MockTestplanClient)(nil).GetTestConfigurationById), ctx, args)
}

// GetTestConfigurations mocks base method.
func (m *MockTestplanClient) GetTestConfigurations(ctx context.Context, args testplan.GetTestConfigurationsArgs) (*testplan.GetTestConfigurationsResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestConfigurations", ctx, args)
	ret0, _ := ret[0].(*testplan.GetTestConfigurationsResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestConfigurations indicates an expected call of GetTestConfigurations.
func (mr *MockTestplanClientMockRecorder) GetTestConfigurations(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestConfigurations", reflect.TypeOf((*MockTestplanClient)(nil).GetTestConfigurations), ctx, args)
}

// GetTestPlanById mocks base method.
func (m *MockTestplanClient) GetTestPlanById(ctx context.Context, args testplan.GetTestPlanByIdArgs) (*testplan.TestPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestPlanById", ctx, args)
	ret0, _ := ret[0].(*testplan.TestPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestPlanById indicates an expected call of GetTestPlanById.
func (mr *MockTestplanClientMockRecorder) GetTestPlanById(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestPlanById", reflect.TypeOf((*MockTestplanClient)(nil).GetTestPlanById), ctx, args)
}

// GetTestPlans mocks base method.
func (m *MockTestplanClient) GetTestPlans(ctx context.Context, args testplan.GetTestPlansArgs) (*testplan.GetTestPlansResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestPlans", ctx, args)
	ret0, _ := ret[0].(*testplan.GetTestPlansResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestPlans indicates an expected call of GetTestPlans.
func (mr *MockTestplanClientMockRecorder) GetTestPlans(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestPlans", reflect.TypeOf((*MockTestplanClient)(nil).GetTestPlans), ctx, args)
}

// GetTestSuiteById mocks base method.
func (m *MockTestplanClient) GetTestSuiteById(ctx context.Context, args testplan.GetTestSuiteByIdArgs) (*testplan.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuiteById", ctx, args)
	ret0, _ := ret[0].(*testplan.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuiteById indicates an expected call of GetTestSuiteById.
func (mr *MockTestplanClientMockRecorder) GetTestSuiteById(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuiteById", reflect.TypeOf((*MockTestplanClient)(nil).GetTestSuiteById), ctx, args)
}

// GetTestSuitesForPlan mocks base method.
func (m *MockTestplanClient) GetTestSuitesForPlan(ctx context.Context, args testplan.GetTestSuitesForPlanArgs) (*testplan.GetTestSuitesForPlanResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuitesForPlan", ctx, args)
	ret0, _ := ret[0].(*testplan.GetTestSuitesForPlanResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuitesForPlan indicates an expected call of GetTestSuitesForPlan.
func (mr *MockTestplanClientMockRecorder) GetTestSuitesForPlan(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuitesForPlan", reflect.TypeOf((*MockTestplanClient)(nil).GetTestSuitesForPlan), ctx, args)
}

// GetTestVariableById mocks base method.
func (m *MockTestplanClient) GetTestVariableById(ctx context.Context, args testplan.GetTestVariableByIdArgs) (*testplan.TestVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestVariableById", ctx, args)
	ret0, _ := ret[0].(*testplan.TestVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestVariableById indicates an expected call of GetTestVariableById.
func (mr *MockTestplanClientMockRecorder) GetTestVariableById(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestVariableById", reflect.TypeOf((*MockTestplanClient)(nil).GetTestVariableById), ctx, args)
}

// GetTestVariables mocks base method.
func (m *MockTestplanClient) GetTestVariables(ctx context.Context, args testplan.GetTestVariablesArgs) (*testplan.GetTestVariablesResponseValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestVariables", ctx, args)
	ret0, _ := ret[0].(*testplan.GetTestVariablesResponseValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestVariables indicates an expected call of GetTestVariables.
func (mr *MockTestplanClientMockRecorder) GetTestVariables(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestVariables", reflect.TypeOf((*MockTestplanClient)(nil).GetTestVariables), ctx, args)
}

// RemoveTestCasesFromSuite mocks base method.
func (m *MockTestplanClient) RemoveTestCasesFromSuite(ctx context.Context, args testplan.RemoveTestCasesFromSuiteArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTestCasesFromSuite", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTestCasesFromSuite indicates an expected call of RemoveTestCasesFromSuite.
func (mr *MockTestplanClientMockRecorder) RemoveTestCasesFromSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTestCasesFromSuite", reflect.TypeOf((*MockTestplanClient)(nil).RemoveTestCasesFromSuite), ctx, args)
}

// RemoveTestCasesListFromSuite mocks base method.
func (m *MockTestplanClient) RemoveTestCasesListFromSuite(ctx context.Context, args testplan.RemoveTestCasesListFromSuiteArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTestCasesListFromSuite", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTestCasesListFromSuite indicates an expected call of RemoveTestCasesListFromSuite.
func (mr *MockTestplanClientMockRecorder) RemoveTestCasesListFromSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTestCasesListFromSuite", reflect.TypeOf((*MockTestplanClient)(nil).RemoveTestCasesListFromSuite), ctx, args)
}

// ReorderSuiteEntries mocks base method.
func (m *MockTestplanClient) ReorderSuiteEntries(ctx context.Context, args testplan.ReorderSuiteEntriesArgs) (*[]testplan.SuiteEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderSuiteEntries", ctx, args)
	ret0, _ := ret[0].(*[]testplan.SuiteEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderSuiteEntries indicates an expected call of ReorderSuiteEntries.
func (mr *MockTestplanClientMockRecorder) ReorderSuiteEntries(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderSuiteEntries", reflect.TypeOf((*MockTestplanClient)(nil).ReorderSuiteEntries), ctx, args)
}

// UpdateSuiteTestCases mocks base method.
func (m *MockTestplanClient) UpdateSuiteTestCases(ctx context.Context, args testplan.UpdateSuiteTestCasesArgs) (*[]testplan.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSuiteTestCases", ctx, args)
	ret0, _ := ret[0].(*[]testplan.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSuiteTestCases indicates an expected call of UpdateSuiteTestCases.
func (mr *MockTestplanClientMockRecorder) UpdateSuiteTestCases(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuiteTestCases", reflect.TypeOf((*MockTestplanClient)(nil).UpdateSuiteTestCases), ctx, args)
}

// UpdateTestConfiguration mocks base method.
func (m *MockTestplanClient) UpdateTestConfiguration(ctx context.Context, args testplan.UpdateTestConfigurationArgs) (*testplan.TestConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestConfiguration", ctx, args)
	ret0, _ := ret[0].(*testplan.TestConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTestConfiguration indicates an expected call of UpdateTestConfiguration.
func (mr *MockTestplanClientMockRecorder) UpdateTestConfiguration(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestConfiguration", reflect.TypeOf((*MockTestplanClient)(nil).UpdateTestConfiguration), ctx, args)
}

// UpdateTestPlan mocks base method.
func (m *MockTestplanClient) UpdateTestPlan(ctx context.Context, args testplan.UpdateTestPlanArgs) (*testplan.TestPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestPlan", ctx, args)
	ret0, _ := ret[0].(*testplan.TestPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTestPlan indicates an expected call of UpdateTestPlan.
func (mr *MockTestplanClientMockRecorder) UpdateTestPlan(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestPlan", reflect.TypeOf((*MockTestplanClient)(nil).UpdateTestPlan), ctx, args)
}

// UpdateTestPoints mocks base method.
func (m *MockTestplanClient) UpdateTestPoints(ctx context.Context, args testplan.UpdateTestPointsArgs) (*[]testplan.TestPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestPoints", ctx, args)
	ret0, _ := ret[0].(*[]testplan.TestPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTestPoints indicates an expected call of UpdateTestPoints.
func (mr *MockTestplanClientMockRecorder) UpdateTestPoints(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestPoints", reflect.TypeOf((*MockTestplanClient)(nil).UpdateTestPoints), ctx, args)
}

// UpdateTestSuite mocks base method.
func (m *MockTestplanClient) UpdateTestSuite(ctx context.Context, args testplan.UpdateTestSuiteArgs) (*testplan.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestSuite", ctx, args)
	ret0, _ := ret[0].(*testplan.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTestSuite indicates an expected call of UpdateTestSuite.
func (mr *MockTestplanClientMockRecorder) UpdateTestSuite(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestSuite", reflect.TypeOf((*MockTestplanClient)(nil).UpdateTestSuite), ctx, args)
}

// UpdateTestVariable mocks base method.
func (m *MockTestplanClient) UpdateTestVariable(ctx context.Context, args testplan.UpdateTestVariableArgs) (*testplan.TestVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestVariable", ctx, args)
	ret0, _ := ret[0].(*testplan.TestVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTestVariable indicates an expected call of UpdateTestVariable.
func (mr *MockTestplanClientMockRecorder) UpdateTestVariable(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestVariable", reflect.TypeOf((*MockTestplanClient)(nil).UpdateTestVariable), ctx, args)
}
