//go:build (all || resource_feature_flag) && !exclude_resource_feature_flag

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-devops-go-api/azuredevops/v7/featuremanagement (interfaces: Client)

package featuremanagement

import (
	context "context"
	reflect "reflect"

	featuremanagement "github.com/microsoft/azure-devops-go-api/azuredevops/v7/featuremanagement"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of featuremanagement.Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetFeature mocks base method.
func (m *MockClient) GetFeature(arg0 context.Context, arg1 featuremanagement.GetFeatureArgs) (*featuremanagement.ContributedFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeature", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeature indicates an expected call of GetFeature.
func (mr *MockClientMockRecorder) GetFeature(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeature", reflect.TypeOf((*MockClient)(nil).GetFeature), arg0, arg1)
}

// GetFeatureState mocks base method.
func (m *MockClient) GetFeatureState(arg0 context.Context, arg1 featuremanagement.GetFeatureStateArgs) (*featuremanagement.ContributedFeatureState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureState", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureState indicates an expected call of GetFeatureState.
func (mr *MockClientMockRecorder) GetFeatureState(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureState", reflect.TypeOf((*MockClient)(nil).GetFeatureState), arg0, arg1)
}

// GetFeatureStateForScope mocks base method.
func (m *MockClient) GetFeatureStateForScope(arg0 context.Context, arg1 featuremanagement.GetFeatureStateForScopeArgs) (*featuremanagement.ContributedFeatureState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureStateForScope", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureStateForScope indicates an expected call of GetFeatureStateForScope.
func (mr *MockClientMockRecorder) GetFeatureStateForScope(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureStateForScope", reflect.TypeOf((*MockClient)(nil).GetFeatureStateForScope), arg0, arg1)
}

// GetFeatures mocks base method.
func (m *MockClient) GetFeatures(arg0 context.Context, arg1 featuremanagement.GetFeaturesArgs) (*[]featuremanagement.ContributedFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatures", arg0, arg1)
	ret0, _ := ret[0].(*[]featuremanagement.ContributedFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatures indicates an expected call of GetFeatures.
func (mr *MockClientMockRecorder) GetFeatures(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatures", reflect.TypeOf((*MockClient)(nil).GetFeatures), arg0, arg1)
}

// QueryFeatureStates mocks base method.
func (m *MockClient) QueryFeatureStates(arg0 context.Context, arg1 featuremanagement.QueryFeatureStatesArgs) (*featuremanagement.ContributedFeatureStateQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFeatureStates", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureStateQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFeatureStates indicates an expected call of QueryFeatureStates.
func (mr *MockClientMockRecorder) QueryFeatureStates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFeatureStates", reflect.TypeOf((*MockClient)(nil).QueryFeatureStates), arg0, arg1)
}

// QueryFeatureStatesForDefaultScope mocks base method.
func (m *MockClient) QueryFeatureStatesForDefaultScope(arg0 context.Context, arg1 featuremanagement.QueryFeatureStatesForDefaultScopeArgs) (*featuremanagement.ContributedFeatureStateQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFeatureStatesForDefaultScope", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureStateQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFeatureStatesForDefaultScope indicates an expected call of QueryFeatureStatesForDefaultScope.
func (mr *MockClientMockRecorder) QueryFeatureStatesForDefaultScope(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFeatureStatesForDefaultScope", reflect.TypeOf((*MockClient)(nil).QueryFeatureStatesForDefaultScope), arg0, arg1)
}

// QueryFeatureStatesForNamedScope mocks base method.
func (m *MockClient) QueryFeatureStatesForNamedScope(arg0 context.Context, arg1 featuremanagement.QueryFeatureStatesForNamedScopeArgs) (*featuremanagement.ContributedFeatureStateQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFeatureStatesForNamedScope", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureStateQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFeatureStatesForNamedScope indicates an expected call of QueryFeatureStatesForNamedScope.
func (mr *MockClientMockRecorder) QueryFeatureStatesForNamedScope(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFeatureStatesForNamedScope", reflect.TypeOf((*MockClient)(nil).QueryFeatureStatesForNamedScope), arg0, arg1)
}

// SetFeatureState mocks base method.
func (m *MockClient) SetFeatureState(arg0 context.Context, arg1 featuremanagement.SetFeatureStateArgs) (*featuremanagement.ContributedFeatureState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeatureState", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFeatureState indicates an expected call of SetFeatureState.
func (mr *MockClientMockRecorder) SetFeatureState(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeatureState", reflect.TypeOf((*MockClient)(nil).SetFeatureState), arg0, arg1)
}

// SetFeatureStateForScope mocks base method.
func (m *MockClient) SetFeatureStateForScope(arg0 context.Context, arg1 featuremanagement.SetFeatureStateForScopeArgs) (*featuremanagement.ContributedFeatureState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeatureStateForScope", arg0, arg1)
	ret0, _ := ret[0].(*featuremanagement.ContributedFeatureState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFeatureStateForScope indicates an expected call of SetFeatureStateForScope.
func (mr *MockClientMockRecorder) SetFeatureStateForScope(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeatureStateForScope", reflect.TypeOf((*MockClient)(nil).SetFeatureStateForScope), arg0, arg1)
}
