name: Go lint

on:
  pull_request:
    branches: [ "main" ]

jobs:

  go-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - uses: golangci/golangci-lint-action@v7
      with:
        version: 'v2.12.2'
        args: -v ./azuredevops/...
        only-new-issues: true
